docker run -dit -v scripts:/jd/scripts -v config:/jd/config -v log:/jd/log -p 5678:5678 -e ENABLE_HANGUP=true -e ENABLE_WEB_PANEL=true --name jd --network bridge --hostname jd --restart always ronghuaxueleng/jd

docker run -dit -v /home/myid/jd/jishui/scripts:/jd/scripts -v /home/myid/jd/jishui/config:/jd/config -v /home/myid/jd/jishui/log:/jd/log -p 5680:5678 -e ENABLE_HANGUP=true -e ENABLE_WEB_PANEL=true --name jd --network bridge --hostname jd --restart always ronghuaxueleng/jd
