version: '3'
services:
  clash:
    image: dreamacro/clash
    container_name: clash
    volumes:
      - ./config/:/root/.config/clash/
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090"
    restart: unless-stopped
    network_mode: "bridge"
