name: "构建Docker镜像0904"
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建Github镜像
    steps:
      - name: Checkout source
        uses: actions/checkout@master
        with: 
          ref: new0904
      - name: docker build and push
        run: |
          cd docker
          docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
          docker build -t ronghuaxueleng/jd .
          docker push ronghuaxueleng/jd
      - name: 删除过多的workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: 1