name: 京东水果
on:
  # schedule:
    # - cron: "0 1,13 * * 1,5,6"
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 下载脚本
        run: |
          wget -q https://raw.githubusercontent.com/ronghuaxueleng/my_actions/qinglong/getToken.py -O getToken.py
          wget -q https://raw.githubusercontent.com/ronghuaxueleng/my_actions/qinglong/USER_AGENTS.js -O USER_AGENTS.js
          wget -q https://raw.githubusercontent.com/ronghuaxueleng/my_actions/qinglong/jdCookie.js -O jdCookie.js
          wget -q https://raw.githubusercontent.com/ronghuaxueleng/my_actions/qinglong/jd_fruit.js -O jd_fruit.js
          wget -q https://raw.githubusercontent.com/ronghuaxueleng/my_actions/qinglong/package.json -O package.json
          wget -q https://raw.githubusercontent.com/ronghuaxueleng/my_actions/qinglong/sendNotify.js -O sendNotify.js
      - name: 安装Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 生成京东token
        run: |
          pip install requests
          python3 getToken.py
      - name: 安装Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: 执行脚本
        run: |
          npm install && node jd_fruit.js
      - name: 删除过多的workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: 30
